{{- if .Values.enableKueueViz }}
apiVersion: v1
kind: Service
metadata:
  name: kueue-viz-backend
  namespace: '{{ .Release.Namespace }}'
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: kueue-viz-backend
{{- end }}
