{{- if .Values.kueueViz.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: kueue-viz-frontend
  namespace: {{ .Values.kueueViz.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: kueue-viz-frontend
{{- end }}

